create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text,
  avatar_url text,
  subscription_status varchar,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.user_profiles
  add column if not exists role text not null default 'viewer';

do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'user_profiles_role_check'
  ) then
    alter table public.user_profiles
      add constraint user_profiles_role_check check (role in ('admin', 'viewer'));
  end if;
end $$;

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1
    from public.user_profiles
    where id = auth.uid()
      and role = 'admin'
  );
$$;

create table if not exists public.admin_audit_logs (
  id bigint generated by default as identity primary key,
  admin_id uuid not null references auth.users(id) on delete cascade,
  action text not null,
  entity_type text not null,
  entity_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.user_profiles enable row level security;
alter table public.memes enable row level security;
alter table public.tags enable row level security;
alter table public.meme_tags enable row level security;
alter table public.interactions enable row level security;
alter table public.admin_audit_logs enable row level security;

drop policy if exists "Admins can read user profiles" on public.user_profiles;
create policy "Admins can read user profiles"
on public.user_profiles
for select
to authenticated
using (public.is_admin() or id = auth.uid());

drop policy if exists "Admins can manage memes" on public.memes;
create policy "Admins can manage memes"
on public.memes
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage tags" on public.tags;
create policy "Admins can manage tags"
on public.tags
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage meme tags" on public.meme_tags;
create policy "Admins can manage meme tags"
on public.meme_tags
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can manage interactions" on public.interactions;
create policy "Admins can manage interactions"
on public.interactions
for all
to authenticated
using (public.is_admin())
with check (public.is_admin());

drop policy if exists "Admins can read audit logs" on public.admin_audit_logs;
create policy "Admins can read audit logs"
on public.admin_audit_logs
for select
to authenticated
using (public.is_admin());

drop policy if exists "Admins can write audit logs" on public.admin_audit_logs;
create policy "Admins can write audit logs"
on public.admin_audit_logs
for insert
to authenticated
with check (public.is_admin() and admin_id = auth.uid());

create index if not exists admin_audit_logs_admin_id_idx
  on public.admin_audit_logs(admin_id);

create index if not exists admin_audit_logs_entity_idx
  on public.admin_audit_logs(entity_type, entity_id);
